name: On push to master

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout full repository history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github

      - name: Enqueue concurrent workflows runs
        uses: softprops/turnstyle@v1
        with:
          abort-after-seconds: 1800
          poll-interval-seconds: 30
          same-branch-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, upload release version to Maven Central and create git release tag with Gradle
        run: ./gradlew final closeAndReleaseRepository printFinalReleaseNode
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GRGIT_USER: ${{ secrets.GRGIT_USER }}
          GRGIT_PASS: ${{ secrets.GRGIT_PASS }}
