name: On push to master

on:
    push:
        branches:
            - master
        paths-ignore:
            - README.md

concurrency: on-push-to-master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v5
                with:
                    fetch-depth: 0

            -   name: Setup Git
                run: |
                    git config user.name "${{ github.actor }}"
                    git config user.email "${{ github.actor }}@users.noreply.github.com"

            -   name: Setup JDK 11
                uses: actions/setup-java@v4
                with:
                    java-version: '11'
                    distribution: 'corretto'
                    cache: 'gradle'

            -   name: Build
                run: ./gradlew final closeAndReleaseStagingRepositories printFinalReleaseNote
                env:
                    GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
                    GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
                    SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                    SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
                    GITHUB_HEAD_REF: ${{ github.head_ref }}
